inherit_from: "configs/rgbd/replica/base_config.yaml"
Dataset:
  orb_settings_path: "configs/orb_config/Replica/office0.yaml"
  dataset_path: "/home/6t/ZJJ/dataset/gsData/Replica/office0/"
  single_thread: False
