inherit_from: "configs/rgbd/tum/base_config.yaml"

Results:
  save_results: False
  save_dir: "results"
  save_trj: False
  save_trj_kf_intv: 0
  use_gui: True
  eval_rendering: False
  use_wandb: False

Dataset:
  dataset_path: "/home/6t/ZJJ/dataset/gsData/TUM/mydata1"
  orb_settings_path: "configs/orb_config/Tum/tum1.yaml"
  Calibration:
    fx: 517.306408
    fy: 516.469215
    cx: 318.643040
    cy: 255.313989
    k1: 0.262383
    k2: -0.953104
    p1: -0.005358
    p2: 0.002628
    k3: 1.163314
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0
    pcd_downsample: 32
    pcd_downsample_init: 32